version: "3.9"
services:
  application:
    container_name: application
    restart: always
    build: ./app
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  redis:
    image: redis:alpine3.16
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /data/lib/birthday/postgresql/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}